/**
 * Writes fixtures/pup-patrol.json: three minutes of the creek's public channels that
 * Pup Patrol reads (Holt A's den view, the Beaver Flats camera trap, and the creek
 * overview), recorded from the simulation as the field station would publish them.
 * The game's repository copies this file for its own fixture mode and tests, so the
 * game never imports this repository.
 *
 *   node scripts/pup-patrol-fixture.ts           write it
 *   node scripts/pup-patrol-fixture.ts --check   exit 1 if it is out of date
 *
 * The window is the first one of the seeded creek in which the pups go out and come
 * home and the trap fires several times, so one replay shows every game state.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJsonPretty, type Json } from "streamotter/contracts";
import { createWorld, currentEmissions, serialize, restore, step, type Emission, type WorldState } from "@lontra-creek/sim";
import { toRecord, type FieldRecord } from "../src/records.ts";

export const PUP_PATROL_KEYS: readonly string[] = ["den:A", "reach:beaver-flats", "creekOverview:lontra"];
const TICKS = 90;
const SEARCH_LIMIT = 40 * 288;

export interface PupPatrolFixture {
  description: string;
  seed: string;
  /** The study tick the recording starts at; `initial` is every channel's state then. */
  startTick: number;
  tickMs: number;
  initial: FieldRecord[];
  /** One entry per tick: the records that tick published (often none for the den or the trap). */
  ticks: FieldRecord[][];
}

function records(emissions: Emission[]): FieldRecord[] {
  return emissions.filter(emission => PUP_PATROL_KEYS.includes(emission.key)).map(emission => toRecord(emission).value);
}

function eventful(world: WorldState): boolean {
  const copy = restore(serialize(world));
  let frames = 0;
  // The pups go out and then come home again, in that order, inside the window.
  let wentOut = false;
  let cameHome = false;
  for (let i = 0; i < TICKS; i++) {
    for (const emission of step(copy)) {
      if (emission.key === "reach:beaver-flats") frames += 1;
      if (emission.key !== "den:A") continue;
      const pups = (emission.data as { pups: string }).pups;
      if (pups === "out") wentOut = true;
      else if (pups === "in-den" && wentOut) cameHome = true;
    }
  }
  return frames >= 5 && cameHome;
}

export function pupPatrolFixture(): PupPatrolFixture {
  const world = createWorld({ seed: "lontra-creek" });
  while (!eventful(world)) {
    if (world.tick > SEARCH_LIMIT) throw new Error("No eventful window in the first forty study days.");
    step(world);
  }
  const startTick = world.tick;
  const initial = records(currentEmissions(world));
  const ticks: FieldRecord[][] = [];
  for (let i = 0; i < TICKS; i++) ticks.push(records(step(world)));
  return {
    description: "Lontra Creek's public den view for Holt A, the Beaver Flats camera trap, and the creek overview, as the field station publishes them. Generated by lontra-creek apps/field-station/scripts/pup-patrol-fixture.ts; do not edit.",
    seed: "lontra-creek",
    startTick,
    tickMs: 2_000,
    initial,
    ticks
  };
}

const path = join(import.meta.dirname, "..", "fixtures", "pup-patrol.json");

if (import.meta.main) {
  const content = canonicalJsonPretty(pupPatrolFixture() as unknown as Json);
  const current = await readFile(path, "utf8").catch(() => null);
  if (process.argv.includes("--check")) {
    if (current !== content) {
      console.error("Out of date: fixtures/pup-patrol.json. Run npm run fixture:pup-patrol in apps/field-station.");
      process.exit(1);
    }
  } else if (current !== content) {
    await writeFile(path, content);
    console.log("Wrote fixtures/pup-patrol.json");
  }
}
